#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     green,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     blue,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     red,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void programtime(int timer)
{
	while(nPgmTime<timer)
	{releaseCPU();}
}

task raiseZElevator()
{
	motor[blue] = 100;
	programtime(5000);
	motor[blue] = 0;
	programtime(15000);
	motor[blue] = -50;
	programtime(20000);
	motor[blue] = 0;
}


task goforward()
{
	motor[red] = -50;
	motor[green] = -50;
	programtime (4000);
	motor[red] = 0;
	motor[green] = -0;
}
task blow()
{
	programtime(7000);
	motor[motorA] = -25;
	programtime(9000);
	motor[motorA] = 0;
}

//#include "JoystickDriver.c"
task main()
{
	//waitForStart();

	startTask(goforward, 10 );

	startTask(raiseZElevator, 10 );

	startTask(blow, 10 );

	releaseCPU();
	wait1Msec(21000);
}
